In [1]:
import torch
import torch.nn.functional as F

# Example embeddings for 3 tokens
x = torch.rand(3,4)

# Random weight matrices
wq = torch.rand(4,4)
wk = torch.rand(4,4)
wv = torch.rand(4,4)

Q = x @ wq
K = x @ wk
v = x @ wv

attention_scores = Q @ K.T
attention_weights = F.softmax(attention_scores,dim=-1)

output = attention_weights @ v

print("Attention Weights:\n", attention_weights)
print("Output:\n", output)

Attention Weights:
 tensor([[0.2081, 0.1146, 0.6773],
        [0.1651, 0.0500, 0.7849],
        [0.1362, 0.0476, 0.8162]])
Output:
 tensor([[1.8574, 1.7341, 1.3128, 1.1625],
        [1.9037, 1.7924, 1.3360, 1.2145],
        [1.9231, 1.8046, 1.3525, 1.2264]])


In [4]:
import torch
import torch.nn.functional as F

x = torch.rand(4,2)

wq = torch.rand(2,3)
wk = torch.rand(2,3) # Changed from (2,2) to (2,3) for consistency with wq's output dimension
wv = torch.rand(2,3) # Changed from (3,3) to (2,3) to match x's embedding dimension (2) and wq's output dimension (3)

Q = x @ wq
K = x @ wk
V = x @ wv

attention_scores = Q @ K.T
attention_weights = F.softmax(attention_scores, dim = -1)

output = attention_weights @ V

print("Attention Weights:\n", attention_weights)
print("Output:\n", output)


Attention Weights:
 tensor([[0.2755, 0.2254, 0.3186, 0.1805],
        [0.2725, 0.2296, 0.3087, 0.1892],
        [0.2780, 0.2217, 0.3274, 0.1729],
        [0.2568, 0.2449, 0.2657, 0.2327]])
Output:
 tensor([[0.5601, 0.9796, 0.8743],
        [0.5547, 0.9694, 0.8652],
        [0.5648, 0.9885, 0.8822],
        [0.5287, 0.9213, 0.8226]])
